name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull Data
        run: |
          echo "Simulate dvc pull"  # لو عندك DVC ممكن تضيفي الأمر الحقيقي

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install mlflow

      - name: Train Model
        run: python train.py

      - name: Upload run info
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - name: Download run info
        uses: actions/download-artifact@v4
        with:
          name: model-info
          path: .

      - name: Check Accuracy Threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          RUN_ID=$(cat model_info.txt)
          echo "Building Docker image for Run ID: $RUN_ID"